services:

  student2-database:
    build:
      context: ./student-2/database
      dockerfile: Dockerfile
    container_name: student2-database
    ports:
      - "5202:5202"
    networks:
      - cafe-network

  student2-backend:
    build:
      context: ./student-2
      dockerfile: backend/Dockerfile
    container_name: student2-backend
    ports:
      - "5201:5201"
    environment:
    - DATABASE_SERVICE_URL=http://student2-database:5202
    depends_on:
      - student2-database
    networks:
      - cafe-network

  student2-frontend:
    build:
      context: ./student-2/frontend
      dockerfile: Dockerfile
    container_name: student2-frontend
    ports:
      - "5200:5200"
    depends_on:
      - student2-backend
    networks:
      - cafe-network

networks:

  cafe-network:
    driver: bridge